trigger: none
# - main

pool:
  vmImage: ubuntu-latest

variables:
  tag: 1.0.0-$(Build.BuildId)

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(2b3cea5b-bb43-41d1-8899-f56ca430e959)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t acrsujith.azurecr.io/webapp:$(tag) app-dotnet
      az acr login -n acrsujith
      docker push acrsujith.azurecr.io/webapp:$(tag)
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace Image TAG'
  inputs:
    rootDirectory: '02_kubernetes_aks'
    targetFiles: 'app-deploy.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '__'
    tokenSuffix: '__'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: true

- script: cat 02_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Visual Studio Premium with MSDN(2b3cea5b-bb43-41d1-8899-f56ca430e959)'
    azureResourceGroup: 'aks-demo'
    kubernetesCluster: 'aks-demo-cluster'
    useClusterAdmin: true
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
